management.endpoints.access.default=none

server.forward-headers-strategy=native

solesonic.mcp.resource=${MCP_REGISTRATION_ENDPOINT}

solesonic.agent.security.enabled=true

spring.ai.openai.base-url=${CHAT_OPENAI_HOST}

spring.ai.model.chat=openai
spring.ai.openai.model=${DEFAULT_CHAT_MODEL}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.model=${EMBEDDING_MODEL}
