management.endpoints.access.default=unrestricted
solesonic.mcp.resource=${MCP_REGISTRATION_ENDPOINT}

logging.level.root=INFO
logging.level.com.solesonic.mcp.security=INFO
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol=TRACE

spring.ai.mcp.server.request-timeout=600s