package com.solesonic.mcp.workflow.sports;

public enum SportsWorkflowStage {
    INITIALIZING,
    PARSING_INTENT,
    RESOLVING_TEAM_URLS,
    FETCHING_ESPN_SCHEDULE,
    FETCHING_ESPN_ROSTER,
    FETCHING_ESPN_STATS,
    FETCHING_ESPN_STANDINGS,
    SEARCHING_NEWS,
    VALIDATING_ROSTER,
    ANALYZING_PLAYER,
    SYNTHESIZING_ANALYSIS,
    COMPLETED,
    FAILED
}
