services:
  solesonic-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: solesonic-mcp-server
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    environment:
      - SERVER_PORT=8081
    restart: unless-stopped