services:
  solesonic-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: solesonic-mcp-server
    ports:
      - "9443:9443"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SSL_CERT_LOCATION=/run/secrets/${SSL_CERT_FILE}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SERVER_PORT=9443
    volumes:
      - ${SYSTEM_SSL_CERT_LOCATION}/${SSL_CERT_FILE}:/run/secrets/${SSL_CERT_FILE}:ro
    restart: no