services:
  solesonic-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: solesonic-mcp-server
    ports:
      - "9443:9443"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod,ssl
      - SSL_CERT_LOCATION=/run/secrets/${SSL_CERT_FILE}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ATLASSIAN_TOKEN_BROKER_ISSUER_URI=${ATLASSIAN_TOKEN_BROKER_ISSUER_URI}
      - ATLASSIAN_TOKEN_BROKER_CLIENT_ID=${ATLASSIAN_TOKEN_BROKER_CLIENT_ID}
      - ATLASSIAN_TOKEN_BROKER_CLIENT_SECRET=${ATLASSIAN_TOKEN_BROKER_CLIENT_SECRET}
      - ATLASSIAN_TOKEN_BROKER_SCOPES=izzy-bot-token-broker/atlassian.read,izzy-bot-token-broker/atlassian.write
      - SERVER_PORT=9443
    volumes:
      - ${SYSTEM_SSL_CERT_LOCATION}/${SSL_CERT_FILE}:/run/secrets/${SSL_CERT_FILE}:ro
    restart: no