services:
  solesonic-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: solesonic-mcp-server
    ports:
      - "8181:8080"
    env_file:
      - .env
    volumes:
      - /var/log/solesonic-mcp-server:/var/log/solesonic-mcp-server
    restart: no