services:
  solesonic-mcp-server:
    env_file:
      - ${ENV_FILE:-.env}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      no_cache: true
    container_name: solesonic-mcp-server
    network_mode: "host"
    environment:
      - SERVER_PORT=8181
    volumes:
      - /var/log/solesonic-mcp-server:/var/log/solesonic-mcp-server
    restart: no